// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"giiku-camp/internal/app/config"
	"giiku-camp/internal/app/container"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func New() (*container.App, error) {
	engine := provideGinEngine()
	configConfig := config.New()
	app := container.NewApp(engine, configConfig)
	return app, nil
}

// wire.go:

func provideGinEngine() *gin.Engine {
	return gin.Default()
}
