// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"giiku-camp/internal/app/config"
	"giiku-camp/internal/app/container"
	"giiku-camp/internal/controller"
	"giiku-camp/internal/infra/apple"
	"giiku-camp/internal/infra/datastore"
	"giiku-camp/internal/middleware"
	"giiku-camp/internal/usecase"
	"giiku-camp/pkg/datastore"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func New() (*container.App, error) {
	engine := provideGinEngine()
	client := datastore.New()
	userRepo := repository.NewUserRepo(client)
	userFriendListRepo := repository.NewUserFriendListRepo(client)
	appleClient, err := apple.New()
	if err != nil {
		return nil, err
	}
	userUsecase := usecase.NewUserUsecase(userRepo, userFriendListRepo, appleClient)
	userCtrl := controller.NewUserCtrl(userUsecase)
	userCrossingRepo := repository.NewUserCrossingRepo(client)
	userCrossingUsecase := usecase.NewUserCrossingUsecase(userCrossingRepo, userRepo)
	userCrossingCtrl := controller.NewUserCrossingCtrl(userCrossingUsecase)
	userFriendListUsecase := usecase.NewUserFriendListUsecase(userFriendListRepo, userRepo, client)
	userFriendListCtrl := controller.NewUserFriendListCtrl(userFriendListUsecase)
	containerContainer := container.NewCtrl(userCtrl, userCrossingCtrl, userFriendListCtrl)
	configConfig := config.New()
	middlewareMiddleware := middleware.NewMiddleware(userRepo)
	app := container.NewApp(engine, containerContainer, configConfig, client, middlewareMiddleware)
	return app, nil
}

// wire.go:

func provideGinEngine() *gin.Engine {
	return gin.Default()
}
