// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/user_friend_list_repo.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/user_friend_list_repo.go -destination=internal/mock/domain/repository/user_friend_list_repo_mock.go -package=mock_repository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	entity "giiku-camp/internal/domain/entity"
	reflect "reflect"

	datastore "cloud.google.com/go/datastore"
	gomock "go.uber.org/mock/gomock"
)

// MockUserFriendListRepo is a mock of UserFriendListRepo interface.
type MockUserFriendListRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserFriendListRepoMockRecorder
	isgomock struct{}
}

// MockUserFriendListRepoMockRecorder is the mock recorder for MockUserFriendListRepo.
type MockUserFriendListRepoMockRecorder struct {
	mock *MockUserFriendListRepo
}

// NewMockUserFriendListRepo creates a new mock instance.
func NewMockUserFriendListRepo(ctrl *gomock.Controller) *MockUserFriendListRepo {
	mock := &MockUserFriendListRepo{ctrl: ctrl}
	mock.recorder = &MockUserFriendListRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserFriendListRepo) EXPECT() *MockUserFriendListRepoMockRecorder {
	return m.recorder
}

// FindByUserID mocks base method.
func (m *MockUserFriendListRepo) FindByUserID(ctx context.Context, userId string) (*entity.UserFriendList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", ctx, userId)
	ret0, _ := ret[0].(*entity.UserFriendList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockUserFriendListRepoMockRecorder) FindByUserID(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockUserFriendListRepo)(nil).FindByUserID), ctx, userId)
}

// Update mocks base method.
func (m *MockUserFriendListRepo) Update(ctx context.Context, userFriendList *entity.UserFriendList) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, userFriendList)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserFriendListRepoMockRecorder) Update(ctx, userFriendList any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserFriendListRepo)(nil).Update), ctx, userFriendList)
}

// UpdateWithTransaction mocks base method.
func (m *MockUserFriendListRepo) UpdateWithTransaction(tx *datastore.Transaction, userFriendList *entity.UserFriendList) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWithTransaction", tx, userFriendList)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWithTransaction indicates an expected call of UpdateWithTransaction.
func (mr *MockUserFriendListRepoMockRecorder) UpdateWithTransaction(tx, userFriendList any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWithTransaction", reflect.TypeOf((*MockUserFriendListRepo)(nil).UpdateWithTransaction), tx, userFriendList)
}
