// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/user_crossing_repo.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/user_crossing_repo.go -destination=internal/mock/domain/repository/user_crossing_repo_mock.go -package=mock_repository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	entity "giiku-camp/internal/domain/entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserCrossingRepo is a mock of UserCrossingRepo interface.
type MockUserCrossingRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserCrossingRepoMockRecorder
	isgomock struct{}
}

// MockUserCrossingRepoMockRecorder is the mock recorder for MockUserCrossingRepo.
type MockUserCrossingRepoMockRecorder struct {
	mock *MockUserCrossingRepo
}

// NewMockUserCrossingRepo creates a new mock instance.
func NewMockUserCrossingRepo(ctrl *gomock.Controller) *MockUserCrossingRepo {
	mock := &MockUserCrossingRepo{ctrl: ctrl}
	mock.recorder = &MockUserCrossingRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserCrossingRepo) EXPECT() *MockUserCrossingRepoMockRecorder {
	return m.recorder
}

// FindByUserID mocks base method.
func (m *MockUserCrossingRepo) FindByUserID(ctx context.Context, userId string) ([]entity.UserCrossing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", ctx, userId)
	ret0, _ := ret[0].([]entity.UserCrossing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockUserCrossingRepoMockRecorder) FindByUserID(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockUserCrossingRepo)(nil).FindByUserID), ctx, userId)
}

// Update mocks base method.
func (m *MockUserCrossingRepo) Update(ctx context.Context, userCrossing entity.UserCrossing) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, userCrossing)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserCrossingRepoMockRecorder) Update(ctx, userCrossing any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserCrossingRepo)(nil).Update), ctx, userCrossing)
}
