// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/usecase.go -destination=internal/mock/usecase/usecase_mock.go -package=mock_usecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	request "giiku-camp/internal/usecase/request"
	response "giiku-camp/internal/usecase/response"
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockUserUsecase is a mock of UserUsecase interface.
type MockUserUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUserUsecaseMockRecorder
	isgomock struct{}
}

// MockUserUsecaseMockRecorder is the mock recorder for MockUserUsecase.
type MockUserUsecaseMockRecorder struct {
	mock *MockUserUsecase
}

// NewMockUserUsecase creates a new mock instance.
func NewMockUserUsecase(ctrl *gomock.Controller) *MockUserUsecase {
	mock := &MockUserUsecase{ctrl: ctrl}
	mock.recorder = &MockUserUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserUsecase) EXPECT() *MockUserUsecaseMockRecorder {
	return m.recorder
}

// GetMe mocks base method.
func (m *MockUserUsecase) GetMe(c *gin.Context) (*response.UserRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMe", c)
	ret0, _ := ret[0].(*response.UserRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMe indicates an expected call of GetMe.
func (mr *MockUserUsecaseMockRecorder) GetMe(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMe", reflect.TypeOf((*MockUserUsecase)(nil).GetMe), c)
}

// RefreshToken mocks base method.
func (m *MockUserUsecase) RefreshToken(c *gin.Context, req request.RefreshTokenReq) (*response.RefreshTokenRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", c, req)
	ret0, _ := ret[0].(*response.RefreshTokenRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockUserUsecaseMockRecorder) RefreshToken(c, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockUserUsecase)(nil).RefreshToken), c, req)
}

// SignIn mocks base method.
func (m *MockUserUsecase) SignIn(c *gin.Context, req request.SignInReq) (*response.SignInRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignIn", c, req)
	ret0, _ := ret[0].(*response.SignInRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignIn indicates an expected call of SignIn.
func (mr *MockUserUsecaseMockRecorder) SignIn(c, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignIn", reflect.TypeOf((*MockUserUsecase)(nil).SignIn), c, req)
}

// SignUp mocks base method.
func (m *MockUserUsecase) SignUp(c *gin.Context, req request.SignUpReq) (*response.SignUpRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignUp", c, req)
	ret0, _ := ret[0].(*response.SignUpRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignUp indicates an expected call of SignUp.
func (mr *MockUserUsecaseMockRecorder) SignUp(c, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignUp", reflect.TypeOf((*MockUserUsecase)(nil).SignUp), c, req)
}

// UpdateMe mocks base method.
func (m *MockUserUsecase) UpdateMe(c *gin.Context, req request.UpdateMeReq) (*response.UserRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMe", c, req)
	ret0, _ := ret[0].(*response.UserRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMe indicates an expected call of UpdateMe.
func (mr *MockUserUsecaseMockRecorder) UpdateMe(c, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMe", reflect.TypeOf((*MockUserUsecase)(nil).UpdateMe), c, req)
}

// MockUserCrossingUsecase is a mock of UserCrossingUsecase interface.
type MockUserCrossingUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUserCrossingUsecaseMockRecorder
	isgomock struct{}
}

// MockUserCrossingUsecaseMockRecorder is the mock recorder for MockUserCrossingUsecase.
type MockUserCrossingUsecaseMockRecorder struct {
	mock *MockUserCrossingUsecase
}

// NewMockUserCrossingUsecase creates a new mock instance.
func NewMockUserCrossingUsecase(ctrl *gomock.Controller) *MockUserCrossingUsecase {
	mock := &MockUserCrossingUsecase{ctrl: ctrl}
	mock.recorder = &MockUserCrossingUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserCrossingUsecase) EXPECT() *MockUserCrossingUsecaseMockRecorder {
	return m.recorder
}

// GetUserCrossing mocks base method.
func (m *MockUserCrossingUsecase) GetUserCrossing(c *gin.Context) (*response.GetUserCrossingRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserCrossing", c)
	ret0, _ := ret[0].(*response.GetUserCrossingRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserCrossing indicates an expected call of GetUserCrossing.
func (mr *MockUserCrossingUsecaseMockRecorder) GetUserCrossing(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserCrossing", reflect.TypeOf((*MockUserCrossingUsecase)(nil).GetUserCrossing), c)
}

// RegisterUserCrossing mocks base method.
func (m *MockUserCrossingUsecase) RegisterUserCrossing(c *gin.Context, req request.RegisterUserCrossingReq) (*response.RegisterUserCrossingRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterUserCrossing", c, req)
	ret0, _ := ret[0].(*response.RegisterUserCrossingRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterUserCrossing indicates an expected call of RegisterUserCrossing.
func (mr *MockUserCrossingUsecaseMockRecorder) RegisterUserCrossing(c, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUserCrossing", reflect.TypeOf((*MockUserCrossingUsecase)(nil).RegisterUserCrossing), c, req)
}

// MockUserFriendListUsecase is a mock of UserFriendListUsecase interface.
type MockUserFriendListUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUserFriendListUsecaseMockRecorder
	isgomock struct{}
}

// MockUserFriendListUsecaseMockRecorder is the mock recorder for MockUserFriendListUsecase.
type MockUserFriendListUsecaseMockRecorder struct {
	mock *MockUserFriendListUsecase
}

// NewMockUserFriendListUsecase creates a new mock instance.
func NewMockUserFriendListUsecase(ctrl *gomock.Controller) *MockUserFriendListUsecase {
	mock := &MockUserFriendListUsecase{ctrl: ctrl}
	mock.recorder = &MockUserFriendListUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserFriendListUsecase) EXPECT() *MockUserFriendListUsecaseMockRecorder {
	return m.recorder
}

// AcceptRequest mocks base method.
func (m *MockUserFriendListUsecase) AcceptRequest(c *gin.Context, req request.AcceptRequestReq) (*response.AcceptRequestRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptRequest", c, req)
	ret0, _ := ret[0].(*response.AcceptRequestRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcceptRequest indicates an expected call of AcceptRequest.
func (mr *MockUserFriendListUsecaseMockRecorder) AcceptRequest(c, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptRequest", reflect.TypeOf((*MockUserFriendListUsecase)(nil).AcceptRequest), c, req)
}

// GetUserFriendList mocks base method.
func (m *MockUserFriendListUsecase) GetUserFriendList(c *gin.Context) (*response.UserFriendListRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserFriendList", c)
	ret0, _ := ret[0].(*response.UserFriendListRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserFriendList indicates an expected call of GetUserFriendList.
func (mr *MockUserFriendListUsecaseMockRecorder) GetUserFriendList(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserFriendList", reflect.TypeOf((*MockUserFriendListUsecase)(nil).GetUserFriendList), c)
}

// SendRequest mocks base method.
func (m *MockUserFriendListUsecase) SendRequest(c *gin.Context, req request.SendRequestReq) (*response.SendRequestRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendRequest", c, req)
	ret0, _ := ret[0].(*response.SendRequestRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendRequest indicates an expected call of SendRequest.
func (mr *MockUserFriendListUsecaseMockRecorder) SendRequest(c, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendRequest", reflect.TypeOf((*MockUserFriendListUsecase)(nil).SendRequest), c, req)
}
