// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://example.com/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.example.com/support",
            "email": "support@example.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/refresh": {
            "post": {
                "description": "トークンの更新",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "トークンの更新",
                "parameters": [
                    {
                        "description": "Refresh token",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/giiku-camp_internal_usecase_request.RefreshTokenReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Token refreshed",
                        "schema": {
                            "$ref": "#/definitions/giiku-camp_internal_usecase_response.RefreshTokenRes"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/giiku-camp_internal_controller_render.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/giiku-camp_internal_controller_render.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/signin": {
            "post": {
                "description": "ユーザー認証",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "ユーザー認証",
                "parameters": [
                    {
                        "description": "User details",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/giiku-camp_internal_usecase_request.SignInReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User authenticated",
                        "schema": {
                            "$ref": "#/definitions/giiku-camp_internal_usecase_response.SignInRes"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/giiku-camp_internal_controller_render.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/giiku-camp_internal_controller_render.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/signup": {
            "post": {
                "description": "ユーザー登録",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "ユーザー登録",
                "parameters": [
                    {
                        "description": "User details",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/giiku-camp_internal_usecase_request.SignUpReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User created",
                        "schema": {
                            "$ref": "#/definitions/giiku-camp_internal_usecase_response.SignUpRes"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/giiku-camp_internal_controller_render.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/giiku-camp_internal_controller_render.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/authenticated/crossing": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "すれ違ったユーザの取得",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Crossing"
                ],
                "summary": "すれ違ったユーザの取得",
                "parameters": [
                    {
                        "description": "User Crossing Details",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/giiku-camp_internal_usecase_request.RegisterUserCrossingReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "UserCrossing created",
                        "schema": {
                            "$ref": "#/definitions/giiku-camp_internal_usecase_response.RegisterUserCrossingRes"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/giiku-camp_internal_controller_render.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/giiku-camp_internal_controller_render.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/authenticated/user": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "ユーザー情報取得",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "ユーザー情報取得",
                "responses": {
                    "200": {
                        "description": "User details",
                        "schema": {
                            "$ref": "#/definitions/giiku-camp_internal_usecase_response.UserRes"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/giiku-camp_internal_controller_render.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/giiku-camp_internal_controller_render.Error"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "ユーザー情報更新",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "ユーザー情報更新",
                "parameters": [
                    {
                        "description": "User details",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/giiku-camp_internal_usecase_request.UpdateMeReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User updated",
                        "schema": {
                            "$ref": "#/definitions/giiku-camp_internal_usecase_response.UserRes"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/giiku-camp_internal_controller_render.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/giiku-camp_internal_controller_render.Error"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Returns \"pong\" if server is working",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Ping the server",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "giiku-camp_internal_controller_render.Error": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 0
                },
                "message": {
                    "type": "string",
                    "example": "error message"
                },
                "status": {
                    "type": "integer",
                    "example": 400
                }
            }
        },
        "giiku-camp_internal_usecase_request.RefreshTokenReq": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzkyMzIwMzMsImlhdCI6MTczNjY0MDAzMywidG9rZW5fdmVyc2lvbiI6NiwidXNlcl9pZCI6IjNlZTAzYWRkLWJjZDItNDU1Zi05OTk0LWY3YWY4NDZjZTY2MiJ9.WJCX_65UJKX-DjUpr9TvbtXsE6ZyUH6NyCLNGwcMWR0"
                }
            }
        },
        "giiku-camp_internal_usecase_request.RegisterUserCrossingReq": {
            "type": "object",
            "required": [
                "user_ids"
            ],
            "properties": {
                "user_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "giiku-camp_internal_usecase_request.SignInReq": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "someone@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "password123"
                }
            }
        },
        "giiku-camp_internal_usecase_request.SignUpReq": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "someone@example.com"
                },
                "github_id": {
                    "type": "string",
                    "example": "someone"
                },
                "name": {
                    "type": "string",
                    "example": "someone"
                },
                "password": {
                    "type": "string",
                    "example": "password123"
                },
                "qiita_id": {
                    "type": "string",
                    "example": "someone"
                },
                "x_id": {
                    "type": "string",
                    "example": "someone"
                },
                "zenn_id": {
                    "type": "string",
                    "example": "someone"
                }
            }
        },
        "giiku-camp_internal_usecase_request.UpdateMeReq": {
            "type": "object",
            "properties": {
                "github_id": {
                    "type": "string",
                    "example": "someone"
                },
                "name": {
                    "type": "string",
                    "example": "someone"
                },
                "qiita_id": {
                    "type": "string",
                    "example": "someone"
                },
                "x_id": {
                    "type": "string",
                    "example": "someone"
                },
                "zenn_id": {
                    "type": "string",
                    "example": "someone"
                }
            }
        },
        "giiku-camp_internal_usecase_response.RefreshTokenRes": {
            "type": "object",
            "properties": {
                "token": {
                    "$ref": "#/definitions/giiku-camp_internal_usecase_response.TokenRes"
                }
            }
        },
        "giiku-camp_internal_usecase_response.RegisterUserCrossingRes": {
            "type": "object",
            "properties": {
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/giiku-camp_internal_usecase_response.UserRes"
                    }
                }
            }
        },
        "giiku-camp_internal_usecase_response.SignInRes": {
            "type": "object",
            "properties": {
                "token": {
                    "$ref": "#/definitions/giiku-camp_internal_usecase_response.TokenRes"
                },
                "user": {
                    "$ref": "#/definitions/giiku-camp_internal_usecase_response.UserRes"
                }
            }
        },
        "giiku-camp_internal_usecase_response.SignUpRes": {
            "type": "object",
            "properties": {
                "token": {
                    "$ref": "#/definitions/giiku-camp_internal_usecase_response.TokenRes"
                },
                "user": {
                    "$ref": "#/definitions/giiku-camp_internal_usecase_response.UserRes"
                }
            }
        },
        "giiku-camp_internal_usecase_response.TokenRes": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzY2NDM2MzMsImlhdCI6MTczNjY0MDAzMywidXNlcl9pZCI6IjNlZTAzYWRkLWJjZDItNDU1Zi05OTk0LWY3YWY4NDZjZTY2MiJ9.QbduICi7TKkVnRckCJbTCYurvmBnXQlmclSm7BKsLxo"
                },
                "refresh_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzkyMzIwMzMsImlhdCI6MTczNjY0MDAzMywidG9rZW5fdmVyc2lvbiI6NiwidXNlcl9pZCI6IjNlZTAzYWRkLWJjZDItNDU1Zi05OTk0LWY3YWY4NDZjZTY2MiJ9.WJCX_65UJKX-DjUpr9TvbtXsE6ZyUH6NyCLNGwcMWR0"
                }
            }
        },
        "giiku-camp_internal_usecase_response.UserRes": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2025-01-10T16:45:40.876773Z"
                },
                "email": {
                    "type": "string",
                    "example": "someone@example.com"
                },
                "github_id": {
                    "type": "string",
                    "example": "someone"
                },
                "id": {
                    "type": "string",
                    "example": "3ee03add-bcd2-455f-9994-f7af846ce662"
                },
                "name": {
                    "type": "string",
                    "example": "someone"
                },
                "qiita_id": {
                    "type": "string",
                    "example": "someone"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2025-01-12T00:21:57.251469Z"
                },
                "x_id": {
                    "type": "string",
                    "example": "someone"
                },
                "zenn_id": {
                    "type": "string",
                    "example": "someone"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Giiku Camp API",
	Description:      "This is the Giiku Camp API server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
