basePath: /
definitions:
  giiku-camp_internal_controller_render.Error:
    properties:
      code:
        type: integer
      message:
        type: string
      status:
        type: integer
    type: object
  giiku-camp_internal_usecase_request.CreateUserRequest:
    properties:
      email:
        type: string
      password:
        type: string
      user_name:
        type: string
    type: object
  giiku-camp_internal_usecase_response.CreateUserResponse:
    properties:
      created_at:
        type: string
      email:
        type: string
      updated_at:
        type: string
      user_name:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@example.com
    name: API Support
    url: http://www.example.com/support
  description: This is the Giiku Camp API server.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://example.com/terms/
  title: Giiku Camp API
  version: "1.0"
paths:
  /ping:
    get:
      description: Returns "pong" if server is working
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Ping the server
      tags:
      - Health
  /signup:
    post:
      consumes:
      - application/json
      description: ユーザー登録
      parameters:
      - description: User details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/giiku-camp_internal_usecase_request.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User created
          schema:
            $ref: '#/definitions/giiku-camp_internal_usecase_response.CreateUserResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/giiku-camp_internal_controller_render.Error'
      summary: ユーザー登録
      tags:
      - User
  /users:
    post:
      consumes:
      - application/json
      description: Create new user by providing user details
      parameters:
      - description: User details
        in: body
        name: user
        required: true
        schema:
          additionalProperties: true
          type: object
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Create user
      tags:
      - User
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
