basePath: /
definitions:
  giiku-camp_internal_controller_render.Error:
    properties:
      code:
        example: 0
        type: integer
      message:
        example: error message
        type: string
      status:
        example: 400
        type: integer
    type: object
  giiku-camp_internal_usecase_request.AcceptRequestReq:
    properties:
      type:
        type: string
      userID:
        description: param
        type: string
    required:
    - type
    type: object
  giiku-camp_internal_usecase_request.RefreshTokenReq:
    properties:
      refresh_token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzkyMzIwMzMsImlhdCI6MTczNjY0MDAzMywidG9rZW5fdmVyc2lvbiI6NiwidXNlcl9pZCI6IjNlZTAzYWRkLWJjZDItNDU1Zi05OTk0LWY3YWY4NDZjZTY2MiJ9.WJCX_65UJKX-DjUpr9TvbtXsE6ZyUH6NyCLNGwcMWR0
        type: string
    required:
    - refresh_token
    type: object
  giiku-camp_internal_usecase_request.RegisterUserCrossingReq:
    properties:
      user_ids:
        items:
          type: string
        type: array
    required:
    - user_ids
    type: object
  giiku-camp_internal_usecase_request.SendRequestReq:
    properties:
      user_id:
        type: string
    required:
    - user_id
    type: object
  giiku-camp_internal_usecase_request.SignInReq:
    properties:
      auth_provider:
        example: apple
        type: string
      authorization_code:
        example: authorization_code
        type: string
    required:
    - auth_provider
    - authorization_code
    type: object
  giiku-camp_internal_usecase_request.SignUpReq:
    properties:
      auth_provider:
        example: apple
        type: string
      authorization_code:
        example: authorization_code
        type: string
      github_id:
        example: someone
        type: string
      name:
        example: someone
        type: string
      qiita_id:
        example: someone
        type: string
      x_id:
        example: someone
        type: string
      zenn_id:
        example: someone
        type: string
    required:
    - auth_provider
    - authorization_code
    - name
    type: object
  giiku-camp_internal_usecase_request.UpdateMeReq:
    properties:
      description:
        example: I'm someone
        type: string
      github_id:
        example: someone
        type: string
      name:
        example: someone
        type: string
      qiita_id:
        example: someone
        type: string
      x_id:
        example: someone
        type: string
      zenn_id:
        example: someone
        type: string
    type: object
  giiku-camp_internal_usecase_response.AcceptRequestRes:
    properties:
      ok:
        type: boolean
    type: object
  giiku-camp_internal_usecase_response.CrossedUserRes:
    properties:
      github_id:
        type: string
      id:
        type: string
      name:
        type: string
      qiita_id:
        type: string
      x_id:
        type: string
      zenn_id:
        type: string
    type: object
  giiku-camp_internal_usecase_response.GetUserCrossingRes:
    properties:
      users:
        items:
          $ref: '#/definitions/giiku-camp_internal_usecase_response.CrossedUserRes'
        type: array
    type: object
  giiku-camp_internal_usecase_response.RefreshTokenRes:
    properties:
      token:
        $ref: '#/definitions/giiku-camp_internal_usecase_response.TokenRes'
    type: object
  giiku-camp_internal_usecase_response.RegisterUserCrossingRes:
    properties:
      users:
        items:
          $ref: '#/definitions/giiku-camp_internal_usecase_response.CrossedUserRes'
        type: array
    type: object
  giiku-camp_internal_usecase_response.RejectRequestRes:
    properties:
      ok:
        type: boolean
    type: object
  giiku-camp_internal_usecase_response.SendRequestRes:
    properties:
      ok:
        type: boolean
    type: object
  giiku-camp_internal_usecase_response.SignInRes:
    properties:
      token:
        $ref: '#/definitions/giiku-camp_internal_usecase_response.TokenRes'
      user:
        $ref: '#/definitions/giiku-camp_internal_usecase_response.UserRes'
    type: object
  giiku-camp_internal_usecase_response.SignUpRes:
    properties:
      token:
        $ref: '#/definitions/giiku-camp_internal_usecase_response.TokenRes'
      user:
        $ref: '#/definitions/giiku-camp_internal_usecase_response.UserRes'
    type: object
  giiku-camp_internal_usecase_response.TokenRes:
    properties:
      access_token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzY2NDM2MzMsImlhdCI6MTczNjY0MDAzMywidXNlcl9pZCI6IjNlZTAzYWRkLWJjZDItNDU1Zi05OTk0LWY3YWY4NDZjZTY2MiJ9.QbduICi7TKkVnRckCJbTCYurvmBnXQlmclSm7BKsLxo
        type: string
      refresh_token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzkyMzIwMzMsImlhdCI6MTczNjY0MDAzMywidG9rZW5fdmVyc2lvbiI6NiwidXNlcl9pZCI6IjNlZTAzYWRkLWJjZDItNDU1Zi05OTk0LWY3YWY4NDZjZTY2MiJ9.WJCX_65UJKX-DjUpr9TvbtXsE6ZyUH6NyCLNGwcMWR0
        type: string
    type: object
  giiku-camp_internal_usecase_response.UserFriendRes:
    properties:
      friends:
        items:
          $ref: '#/definitions/giiku-camp_internal_usecase_response.UserRes'
        type: array
      received_requests:
        items:
          $ref: '#/definitions/giiku-camp_internal_usecase_response.UserRes'
        type: array
      sent_requests:
        items:
          $ref: '#/definitions/giiku-camp_internal_usecase_response.UserRes'
        type: array
    type: object
  giiku-camp_internal_usecase_response.UserRes:
    properties:
      created_at:
        example: "2025-01-10T16:45:40.876773Z"
        type: string
      github_id:
        example: someone
        type: string
      id:
        example: 3ee03add-bcd2-455f-9994-f7af846ce662
        type: string
      name:
        example: someone
        type: string
      qiita_id:
        example: someone
        type: string
      updated_at:
        example: "2025-01-12T00:21:57.251469Z"
        type: string
      x_id:
        example: someone
        type: string
      zenn_id:
        example: someone
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@example.com
    name: API Support
    url: http://www.example.com/support
  description: This is the Giiku Camp API server.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://example.com/terms/
  title: Giiku Camp API
  version: "1.0"
paths:
  /api/v1/auth/refresh:
    post:
      consumes:
      - application/json
      description: トークンの更新
      parameters:
      - description: Refresh token
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/giiku-camp_internal_usecase_request.RefreshTokenReq'
      produces:
      - application/json
      responses:
        "200":
          description: Token refreshed
          schema:
            $ref: '#/definitions/giiku-camp_internal_usecase_response.RefreshTokenRes'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/giiku-camp_internal_controller_render.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/giiku-camp_internal_controller_render.Error'
      summary: トークンの更新
      tags:
      - User
  /api/v1/auth/signin:
    post:
      consumes:
      - application/json
      description: ユーザー認証
      parameters:
      - description: User details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/giiku-camp_internal_usecase_request.SignInReq'
      produces:
      - application/json
      responses:
        "200":
          description: User authenticated
          schema:
            $ref: '#/definitions/giiku-camp_internal_usecase_response.SignInRes'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/giiku-camp_internal_controller_render.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/giiku-camp_internal_controller_render.Error'
      summary: ユーザー認証
      tags:
      - User
  /api/v1/auth/signup:
    post:
      consumes:
      - application/json
      description: ユーザー登録
      parameters:
      - description: User details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/giiku-camp_internal_usecase_request.SignUpReq'
      produces:
      - application/json
      responses:
        "200":
          description: User created
          schema:
            $ref: '#/definitions/giiku-camp_internal_usecase_response.SignUpRes'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/giiku-camp_internal_controller_render.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/giiku-camp_internal_controller_render.Error'
      summary: ユーザー登録
      tags:
      - User
  /api/v1/authenticated/crossing:
    get:
      consumes:
      - application/json
      description: すれ違ったユーザの取得
      produces:
      - application/json
      responses:
        "200":
          description: UserCrossing created
          schema:
            $ref: '#/definitions/giiku-camp_internal_usecase_response.GetUserCrossingRes'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/giiku-camp_internal_controller_render.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/giiku-camp_internal_controller_render.Error'
      security:
      - BearerAuth: []
      summary: すれ違ったユーザの取得
      tags:
      - Crossing
    post:
      consumes:
      - application/json
      description: すれ違ったユーザの登録
      parameters:
      - description: User Crossing Details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/giiku-camp_internal_usecase_request.RegisterUserCrossingReq'
      produces:
      - application/json
      responses:
        "200":
          description: UserCrossing created
          schema:
            $ref: '#/definitions/giiku-camp_internal_usecase_response.RegisterUserCrossingRes'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/giiku-camp_internal_controller_render.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/giiku-camp_internal_controller_render.Error'
      security:
      - BearerAuth: []
      summary: すれ違ったユーザの登録
      tags:
      - Crossing
  /api/v1/authenticated/friend:
    get:
      consumes:
      - application/json
      description: フレンド情報取得
      produces:
      - application/json
      responses:
        "200":
          description: Friend details
          schema:
            $ref: '#/definitions/giiku-camp_internal_usecase_response.UserFriendRes'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/giiku-camp_internal_controller_render.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/giiku-camp_internal_controller_render.Error'
      security:
      - BearerAuth: []
      summary: フレンド情報取得
      tags:
      - Friend
    post:
      consumes:
      - application/json
      description: フレンド依頼送信
      parameters:
      - description: Friend details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/giiku-camp_internal_usecase_request.SendRequestReq'
      produces:
      - application/json
      responses:
        "200":
          description: Friend details
          schema:
            $ref: '#/definitions/giiku-camp_internal_usecase_response.SendRequestRes'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/giiku-camp_internal_controller_render.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/giiku-camp_internal_controller_render.Error'
      security:
      - BearerAuth: []
      summary: フレンド依頼送信
      tags:
      - Friend
  /api/v1/authenticated/friend/{user_id}:
    delete:
      consumes:
      - application/json
      description: フレンド依頼拒否
      produces:
      - application/json
      responses:
        "200":
          description: Friend details
          schema:
            $ref: '#/definitions/giiku-camp_internal_usecase_response.RejectRequestRes'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/giiku-camp_internal_controller_render.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/giiku-camp_internal_controller_render.Error'
      security:
      - BearerAuth: []
      summary: フレンド依頼拒否
      tags:
      - Friend
    patch:
      consumes:
      - application/json
      description: フレンド依頼許可
      parameters:
      - description: Friend details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/giiku-camp_internal_usecase_request.AcceptRequestReq'
      produces:
      - application/json
      responses:
        "200":
          description: Friend details
          schema:
            $ref: '#/definitions/giiku-camp_internal_usecase_response.AcceptRequestRes'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/giiku-camp_internal_controller_render.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/giiku-camp_internal_controller_render.Error'
      security:
      - BearerAuth: []
      summary: フレンド依頼許可
      tags:
      - Friend
  /api/v1/authenticated/user:
    get:
      consumes:
      - application/json
      description: ユーザー情報取得
      produces:
      - application/json
      responses:
        "200":
          description: User details
          schema:
            $ref: '#/definitions/giiku-camp_internal_usecase_response.UserRes'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/giiku-camp_internal_controller_render.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/giiku-camp_internal_controller_render.Error'
      security:
      - BearerAuth: []
      summary: ユーザー情報取得
      tags:
      - User
    put:
      consumes:
      - application/json
      description: ユーザー情報更新
      parameters:
      - description: User details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/giiku-camp_internal_usecase_request.UpdateMeReq'
      produces:
      - application/json
      responses:
        "200":
          description: User updated
          schema:
            $ref: '#/definitions/giiku-camp_internal_usecase_response.UserRes'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/giiku-camp_internal_controller_render.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/giiku-camp_internal_controller_render.Error'
      security:
      - BearerAuth: []
      summary: ユーザー情報更新
      tags:
      - User
  /api/v1/user/{id}:
    get:
      consumes:
      - application/json
      description: ユーザー情報取得
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: User details
          schema:
            $ref: '#/definitions/giiku-camp_internal_usecase_response.CrossedUserRes'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/giiku-camp_internal_controller_render.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/giiku-camp_internal_controller_render.Error'
      summary: ユーザー情報取得
      tags:
      - User
  /ping:
    get:
      description: Returns "pong" if server is working
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Ping the server
      tags:
      - Health
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
